name: app-prod

services:
  api:
    image: gwenael9/converto-api:latest
    env_file:
      - ./.env.prod
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SSL=true
      - RABBITMQ_URL=${RABBITMQ_URL}
    restart: always
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.production
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./gateway/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - frontend
    restart: always
    networks:
      - app-network

  frontend:
    image: gwenael9/converto-frontend:latest
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  microservice-converto:
    image: gwenael9/converto-microservice:latest
    env_file:
      - ./.env.prod
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - RABBITMQ_URL=${RABBITMQ_URL}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge