services:
  api:
    image: gwenael9/converto-api:staging
    env_file:
      - ./.env.staging
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SSL=true
      - RABBITMQ_URL=${RABBITMQ_URL}
    restart: always
    networks:
      - app-network-staging

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.production
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - ./gateway/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - frontend
    restart: always
    networks:
      - app-network-staging

  frontend:
    image: gwenael9/converto-frontend:staging
    environment:
      - NODE_ENV=staging
    restart: unless-stopped
    networks:
      - app-network-staging

  microservice-converto:
    image: gwenael9/converto-microservice:staging
    env_file:
      - ./.env.staging
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - RABBITMQ_URL=${RABBITMQ_URL}
    restart: always
    networks:
      - app-network-staging

networks:
  app-network-staging:
    driver: bridge 