FROM node:20-slim

# Installation de LibreOffice
RUN apt-get update && \
    apt-get install -y libreoffice && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copie des fichiers de dépendances
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du code source
COPY . .

# Création du dossier test-files
RUN mkdir -p test-files

# Commande par défaut pour les tests
CMD ["npm", "run", "test:e2e"] 