name: Branch Protection

on:
  pull_request:
    branches: [main, staging, dev]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "feature/**"

jobs:
  validate-source-branch:
    name: Validate Source Branch
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        if: github.event_name == 'pull_request'
        run: |
          # Pour les PRs vers main
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" != "staging" ]]; then
              echo "❌ Les pull requests vers main doivent venir de la branche staging."
              echo "⚠️  Veuillez créer votre pull request depuis la branche staging."
              exit 1
            fi
          fi

          # Pour les PRs vers staging
          if [[ "${{ github.base_ref }}" == "staging" ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
              echo "❌ Les pull requests vers staging doivent venir de la branche dev."
              echo "⚠️  Veuillez créer votre pull request depuis la branche dev."
              exit 1
            fi
          fi

          # Pour les PRs vers dev
          if [[ "${{ github.base_ref }}" == "dev" ]]; then
            if [[ ! "${{ github.event.pull_request.head.ref }}" =~ ^feature/ && ! "${{ github.event.pull_request.head.ref }}" =~ ^fix/ ]]; then
              echo "❌ Les pull requests vers dev doivent venir d'une branche feature/ ou fix/."
              echo "⚠️  Veuillez créer votre pull request depuis une branche feature/nom-du-dev ou fix/nom-du-dev."
              exit 1
            fi
          fi

      - name: Check feature branch naming
        if: github.event_name == 'push'
        run: |
          if [[ "${{ github.ref_name }}" =~ ^feature/ ]]; then
            if [[ ! "${{ github.ref_name }}" =~ ^feature/[a-z0-9-]+$ ]]; then
              echo "❌ Le nom de la branche feature doit suivre le format: feature/nom-du-dev"
              echo "⚠️  Exemple: feature/ajout-fonctionnalite"
              exit 1
            fi
          fi
