name: Branch Protection

on:
  push:
    branches: [main]

jobs:
  prevent-direct-push:
    name: Prevent direct push to main
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is from staging
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/staging" ]]; then
            echo "Direct pushes to main are not allowed. Please create a pull request from staging."
            exit 1
          fi
