name: Branch Protection

on:
  push:
    branches: [main]

jobs:
  prevent-direct-push:
    name: Prevent direct push to main
    runs-on: ubuntu-latest
    steps:
      - name: Check if push is from staging
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "staging" ]]; then
            echo "❌ Les pull requests vers main doivent venir de la branche staging."
            echo "⚠️  Veuillez créer votre pull request depuis la branche staging."
            exit 1
          fi
