name: Branch Protection

on:
  pull_request:
    branches: [main, staging, dev]
    types: [opened, synchronize, reopened]

jobs:
  validate-source-branch:
    name: Validate Source Branch
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          # Pour les PRs vers main
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" != "staging" ]]; then
              echo "❌ Les pull requests vers main doivent venir de la branche staging."
              echo "⚠️  Veuillez créer votre pull request depuis la branche staging."
              exit 1
            fi
          fi

          # Pour les PRs vers staging
          if [[ "${{ github.base_ref }}" == "staging" ]]; then
            if [[ "${{ github.event.pull_request.head.ref }}" != "dev" ]]; then
              echo "❌ Les pull requests vers staging doivent venir de la branche dev."
              echo "⚠️  Veuillez créer votre pull request depuis la branche dev."
              exit 1
            fi
          fi

          # Pour les PRs vers dev
          if [[ "${{ github.base_ref }}" == "dev" ]]; then
            if [[ ! "${{ github.event.pull_request.head.ref }}" =~ ^feature/ ]]; then
              echo "❌ Les pull requests vers dev doivent venir d'une branche feature/."
              echo "⚠️  Veuillez créer votre pull request depuis une branche feature/nom-du-dev."
              exit 1
            fi
          fi
