name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /opt/app
            # Arrêter les conteneurs sans supprimer les volumes
            docker-compose -f docker-compose.prod.yml down
            # Mettre à jour les images
            docker-compose -f docker-compose.prod.yml pull
            # Redémarrer les conteneurs
            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d
            # Nettoyer les images non utilisées
            docker image prune -f
