name: Pull Request Workflow

on:
  pull_request:
    branches: [main, staging]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: "✅ Validation du code"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file structure
        run: |
          echo "Validating repository structure..."
          if [ ! -d ".github" ]; then
            echo "Error: .github directory is missing"
            exit 1
          fi
          if [ ! -f "README.md" ]; then
            echo "Error: README.md is missing"
            exit 1
          fi
